components:
  schemas:
    ParkingSensor:
      description: Description of a generic measurement entity coming from a device or other data source.
      properties:
        description:
          description: A description of this item
          type: string
          x-ngsi:
            type: Property
        deviceType:
          description: Type of device taking the measurement
          type: string
          x-ngsi:
            model: https://schema.org/Text
            type: Property
        id:
          anyOf:
            - description: Identifier format of any NGSI entity
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
              x-ngsi:
                type: Property
            - description: Identifier format of any NGSI entity
              format: uri
              type: string
              x-ngsi:
                type: Property
          description: Unique identifier of the entity
          x-ngsi:
            type: Property
        location:
          description: 'Geojson reference to the item. It can be Point, LineString, Polygon, MultiPoint, MultiLineString or MultiPolygon'
          oneOf:
            - description: Geojson reference to the item. Point
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    type: number
                  minItems: 2
                  type: array
                type:
                  enum:
                    - Point
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON Point
              type: object
              x-ngsi:
                type: GeoProperty
            - description: Geojson reference to the item. LineString
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      type: number
                    minItems: 2
                    type: array
                  minItems: 2
                  type: array
                type:
                  enum:
                    - LineString
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON LineString
              type: object
              x-ngsi:
                type: GeoProperty
            - description: Geojson reference to the item. Polygon
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      items:
                        type: number
                      minItems: 2
                      type: array
                    minItems: 4
                    type: array
                  type: array
                type:
                  enum:
                    - Polygon
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON Polygon
              type: object
              x-ngsi:
                type: GeoProperty
            - description: Geojson reference to the item. MultiPoint
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      type: number
                    minItems: 2
                    type: array
                  type: array
                type:
                  enum:
                    - MultiPoint
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON MultiPoint
              type: object
              x-ngsi:
                type: GeoProperty
            - description: Geojson reference to the item. MultiLineString
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      items:
                        type: number
                      minItems: 2
                      type: array
                    minItems: 2
                    type: array
                  type: array
                type:
                  enum:
                    - MultiLineString
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON MultiLineString
              type: object
              x-ngsi:
                type: GeoProperty
            - description: Geojson reference to the item. MultiLineString
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      items:
                        items:
                          type: number
                        minItems: 2
                        type: array
                      minItems: 4
                      type: array
                    type: array
                  type: array
                type:
                  enum:
                    - MultiPolygon
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON MultiPolygon
              type: object
              x-ngsi:
                type: GeoProperty
          x-ngsi:
            type: GeoProperty
        measurementType:
          description: The type of measurement to be taken
          type: string
          x-ngsi:
            type: Property
        name:
          description: The name of this item
          type: string
          x-ngsi:
            type: Property
        numValue:
          description: Numerical value of the measurement
          type: number
          x-ngsi:
            model: https://schema.org/Number
            type: Property
        owner:
          description: A List containing a JSON encoded sequence of characters referencing the unique Ids of the owner(s)
          items:
            anyOf:
              - description: Identifier format of any NGSI entity
                maxLength: 256
                minLength: 1
                pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
                type: string
                x-ngsi:
                  type: Property
              - description: Identifier format of any NGSI entity
                format: uri
                type: string
                x-ngsi:
                  type: Property
            description: Unique identifier of the entity
            x-ngsi:
              type: Property
          type: array
          x-ngsi:
            type: Property
        textValue:
          description: Textual value of the measurement
          type: string
          x-ngsi:
            model: https://schema.org/Text
            type: Property
        type:
          description: NGSI Entity type. It has to be Measurement
          enum:
            - DeviceMeasurement
          type: string
          x-ngsi:
            type: Property
        unit:
          description: 'Units of the measurement. In case of use of an acronym use units accepted in [CEFACT](https://www.unece.org/cefact.html) code'
          type: string
          x-ngsi:
            type: Property
      required:
        - id
        - type
      type: object
      x-derived-from: ""
      x-disclaimer: 'Redistribution and use in source and binary forms, with or without modification, are permitted  provided that the license conditions are met. Copyleft (c) 2022 Contributors to Smart Data Models Program'
      x-license-url: https://github.com/smart-data-models/dataModel.Device/blob/master/DeviceMeasurement/LICENSE.md
      x-model-schema: https://smart-data-models.github.io/dataModel.Device/DeviceMeasurement/schema.json
      x-model-tags: ""
      x-version: 0.1.0


info: 
  description: "Base Model Definitions from Smart Data Models"
  title: ParkingSensor Data Model
  version: "1.0.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object
