components:
  schemas:
    ParkingGroup:
      description: 'Parking Group'
      type: object
      properties:
        address:
          description: The mailing address
          properties:
            addressCountry:
              description: 'The country. For example, Spain'
              type: string
              x-ngsi:
                model: https://schema.org/addressCountry
                type: Property
            addressLocality:
              description: 'The locality in which the street address is, and which is in the region'
              type: string
              x-ngsi:
                model: https://schema.org/addressLocality
                type: Property
            addressRegion:
              description: 'The region in which the locality is, and which is in the country'
              type: string
              x-ngsi:
                model: https://schema.org/addressRegion
                type: Property
            district:
              description: 'A district is a type of administrative division that, in some countries, is managed by the local government'
              type: string
              x-ngsi:
                type: Property
            postOfficeBoxNumber:
              description: 'The post office box number for PO box addresses. For example, 03578'
              type: string
              x-ngsi:
                model: https://schema.org/postOfficeBoxNumber
                type: Property
            postalCode:
              description: 'The postal code. For example, 24004'
              type: string
              x-ngsi:
                model: https://schema.org/https://schema.org/postalCode
                type: Property
            streetAddress:
              description: The street address
              type: string
              x-ngsi:
                model: https://schema.org/streetAddress
                type: Property
            streetNr:
              description: Number identifying a specific property on a public street
              type: string
              x-ngsi:
                type: Property
          type: object
          x-ngsi:
            model: https://schema.org/address
            type: Property
        availableSpotNumber:
          description: The number of spots available in this group. It must lower or equal than `totalSpotNumber`
          minimum: 0
          type: number
          x-ngsi:
            model: http://schema.org/Number
            type: Property
        category:
          description: 'Parking Group''s category. Enum:''adjacentSpaces, blueZone, completeFloor, free, feeCharged, greenZone, loadUnloadZone, nonAdjacentSpaces, offStreet, onlyDisabled, onlyElectricalCharging, onlyResidents, onlyWithPermit, onStreet, particularConditionsSpaces, shortTermMediumTermLongTerm, statisticsOnly, vehicleTypeSpaces'''
          items:
            enum:
              - adjacentSpaces
              - blueZone
              - completeFloor
              - free
              - feeCharged
              - greenZone
              - loadUnloadZone
              - nonAdjacentSpaces
              - offStreet
              - onlyDisabled
              - onlyElectricalCharging
              - onlyResidents
              - onlyWithPermit
              - onStreet
              - particularConditionsSpaces
              - shortTermMediumTermLongTerm
              - statisticsOnly
              - vehicleTypeSpaces
            type: string
          type: array
          x-ngsi:
            model: http://schema.org/Text
            type: Property
        dateCreated:
          description: Entity creation timestamp. This will usually be allocated by the storage platform
          format: date-time
          type: string
          x-ngsi:
            type: Property
        dateModified:
          description: Timestamp of the last modification of the entity. This will usually be allocated by the storage platform
          format: date-time
          type: string
          x-ngsi:
            type: Property
        description:
          description: A description of this item
          type: string
          x-ngsi:
            type: Property
        id:
          anyOf:
            - description: Identifier format of any NGSI entity
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
              x-ngsi:
                type: Property
            - description: Identifier format of any NGSI entity
              format: uri
              type: string
              x-ngsi:
                type: Property
          description: Unique identifier of the entity
          x-ngsi:
            type: Property
        location:
          description: 'Geojson reference to the item. It can be Point, LineString, Polygon, MultiPoint, MultiLineString or MultiPolygon'
          oneOf:
            - description: Geojson reference to the item. Point
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    type: number
                  minItems: 2
                  type: array
                type:
                  enum:
                    - Point
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON Point
              type: object
              x-ngsi:
                type: GeoProperty
            - description: Geojson reference to the item. LineString
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      type: number
                    minItems: 2
                    type: array
                  minItems: 2
                  type: array
                type:
                  enum:
                    - LineString
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON LineString
              type: object
              x-ngsi:
                type: GeoProperty
            - description: Geojson reference to the item. Polygon
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      items:
                        type: number
                      minItems: 2
                      type: array
                    minItems: 4
                    type: array
                  type: array
                type:
                  enum:
                    - Polygon
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON Polygon
              type: object
              x-ngsi:
                type: GeoProperty
            - description: Geojson reference to the item. MultiPoint
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      type: number
                    minItems: 2
                    type: array
                  type: array
                type:
                  enum:
                    - MultiPoint
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON MultiPoint
              type: object
              x-ngsi:
                type: GeoProperty
            - description: Geojson reference to the item. MultiLineString
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      items:
                        type: number
                      minItems: 2
                      type: array
                    minItems: 2
                    type: array
                  type: array
                type:
                  enum:
                    - MultiLineString
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON MultiLineString
              type: object
              x-ngsi:
                type: GeoProperty
            - description: Geojson reference to the item. MultiLineString
              properties:
                bbox:
                  items:
                    type: number
                  minItems: 4
                  type: array
                coordinates:
                  items:
                    items:
                      items:
                        items:
                          type: number
                        minItems: 2
                        type: array
                      minItems: 4
                      type: array
                    type: array
                  type: array
                type:
                  enum:
                    - MultiPolygon
                  type: string
              required:
                - type
                - coordinates
              title: GeoJSON MultiPolygon
              type: object
              x-ngsi:
                type: GeoProperty
          x-ngsi:
            type: GeoProperty
        name:
          description: The name of this item
          type: string
          x-ngsi:
            type: Property
        occupancyDetectionType:
          description: 'Allowed values: The following from DATEX II version 2.3 _OccupancyDetectionTypeEnum_. Enum:''balancing, manual, modelBased, none, singleSpaceDetection''. Or any other application-specific'
          items:
            enum:
              - balancing
              - manual
              - modelBased
              - none
              - singleSpaceDetection
            type: string
          minItems: 1
          type: array
          uniqueItems: true
          x-ngsi:
            model: http://schema.org/Text
            type: Property
        owner:
          description: A List containing a JSON encoded sequence of characters referencing the unique Ids of the owner(s)
          items:
            anyOf:
              - description: Identifier format of any NGSI entity
                maxLength: 256
                minLength: 1
                pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
                type: string
                x-ngsi:
                  type: Property
              - description: Identifier format of any NGSI entity
                format: uri
                type: string
                x-ngsi:
                  type: Property
            description: Unique identifier of the entity
            x-ngsi:
              type: Property
          type: array
          x-ngsi:
            type: Property
        parkingMode:
          description: 'Parking mode(s). Applications _SHOULD_ inspect the value of this property at parent''s level if it is not defined. Allowed values: Those defined by the DATEX II version 2.3 _ParkingModeEnum_ enumeration. Enum:''echelonParking, parallelParking, perpendicularParking'''
          items:
            enum:
              - echelonParking
              - parallelParking
              - perpendicularParking
            type: string
          minItems: 1
          type: array
          uniqueItems: true
          x-ngsi:
            model: http://schema.org/Text
            type: Property
        refParkingSite:
          anyOf:
            - description: Identifier format of any NGSI entity
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
              x-ngsi:
                type: Property
            - description: Identifier format of any NGSI entity
              format: uri
              type: string
              x-ngsi:
                type: Property
          description: Parking site to which this zone belongs to. A group cannot be orphan. A group cannot have subgroups. Reference to an OffStreetParking or to an OnStreetParking
          x-ngsi:
            type: Relationship
        totalSpotNumber:
          description: 'The total number of spots pertaining to this group. Allowed values: Any positive integer number or 0. Normative references: DATEX 2 version 2.3 attribute _parkingNumberOfSpaces_ of the _ParkingRecord_ class'
          minimum: 1
          type: number
          x-ngsi:
            model: http://schema.org/Number
            type: Property
        type:
          description: NGSI Entity type. It has to be ParkingGroup
          enum:
            - ParkingGroup
          type: string
          x-ngsi:
            type: Property
      required:
        - id
        - type
        - refParkingSite

info: 
  description: "Base Model Definitions from Smart Data Models"
  title: Parking Group Data Model
  version: "1.0.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object
